name: Manual Test Execution

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'both'
        type: choice
        options:
        - both
        - api
        - ui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-playwright
        playwright install chromium

    - name: Run API tests
      if: ${{ github.event.inputs.test_type == 'api' || github.event.inputs.test_type == 'both' }}
      run: pytest -v -m api --browser chromium

    - name: Run UI tests
      if: ${{ github.event.inputs.test_type == 'ui' || github.event.inputs.test_type == 'both' }}
      run: pytest -v -m ui --browser chromium

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: test-results/